version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - 5001:5001
    environment:
      TASK_MANAGER_REDIS_URL: redis://redis-db:6379
      TASK_MANAGER_SQL_PORT: 3306
      APP_PORT: 5001
      TASK_MANAGER_SQL_HOST: sqldb
      TASK_MANAGER_USER: root
      TASK_MANAGER_PASSWORD: root
      TASK_MANAGER_DATABASE: test

    depends_on:
      - sqldb
      - redis-db

  redis-db:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - docker-tests:/redis/data/db

  sqldb:
    image: mysql:8.0
    volumes:
      - docker-tests:/sql/data/db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "test"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"

volumes:
  docker-tests:
